### ISSUE TITLE
Blank box on some custom ability-fired rituals

### ISSUE THREAD

**Issue by thesePeople** [thesePeople/CustomRitualFramework#6]
I may have just set up the XML incorrectly.

**Comment by arvalaan** [comment]
This needs to be added in the RitualBehaviorDef

`<letterTitle>{RITUAL_labelCap}</letterTitle>
    <letterText>{SPEAKER_labelShort} is giving a {RITUAL_labelIndef}.
      \nIf all goes well, listeners will feel inspired, and gain respect for {SPEAKER_labelShort}. If it goes poorly, the speech will do social damage. Positive effects are reduced for non-{IDEOMEMBERS}.</letterText>`
